version: '3.8'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'salt-postgres'
    environment:
      - POSTGRES_USER=alu
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=radiolife
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

